# -*- coding: utf-8 -*-
"""NN_training_1st_iteration_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g15KGwm-EOlT6OR-HVfTq6KTwYlHu-4x
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
from tensorflow import keras

# %matplotlib inline
import numpy as np
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from sklearn.metrics import roc_curve, roc_auc_score
import joblib
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from collecting_data import *

# Call the function to get X_np, y, and df
X_np, y, df = data_sensor()

def training_model():
    
    print("X_np has been loaded")
    column_means = np.nanmean(X_np, axis=0)
    nan_indices = np.isnan(X_np)
    X_np[nan_indices] = np.take(column_means, np.where(nan_indices)[1])

    

    scaler = MinMaxScaler()
    normalized_features = scaler.fit_transform(X_np)

    normalized_features[0]

    le = preprocessing.LabelEncoder()
    le.fit(df.classification)
    df['categorical_label'] = le.transform(df.classification)
    df['categorical_label']

    y = df.categorical_label

    X_train, X_test, y_train, y_test = train_test_split(
        normalized_features, y, test_size=0.3)

    print(np.count_nonzero(np.isnan(normalized_features)))

    # y_test.shape

    X_train_norm = normalize(X_train)
    # X_train_norm[0]

    # X_train.shape

    model = keras.Sequential([
        # Dense means all the neurons in 1 st layer connect with all the neuron in 2nd layer
        keras.layers.Dense(50, input_shape=(32,), activation='relu'),
        keras.layers.Dense(8, activation='sigmoid')
    ])

    model.compile(
        optimizer='adam',
        # sparce means out output is an integer that is basically train_y
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    model.fit(X_train, y_train, epochs=500)
    print(model.evaluate(X_test, y_test))
    joblib.dump(model, 'data/1st_iteration_NN_model_with_normalizedData.pkl')

    return model, normalized_features, y, le



training_model()
