name: CI for MWAA
on: 
	push:
	  branches:
      - main
	env:
	  BUCKET_NAME : "dags-stock-trader"
	  AWS_REGION : "US East (N. Virginia) us-east-1"
	
	# permission can be added at job level or workflow level
	permissions:
	 id-token: write   # This is required for requesting the JWT
	 contents: read    # This is required for actions/checkout
	
	jobs:
	  deploy:
	    runs-on: ubuntu-latest
	    steps:
	     - name: Git clone the repository
	       uses: actions/checkout@main
	     - name: configure aws credentials
	       uses: aws-actions/configure-aws-credentials@v4
	        with:
	          role-to-assume: arn:aws:iam::1234567890:role/example-role
	          aws-region: ${{ env.AWS_REGION }}
	
	      - name: Sync Airflow files to the MWAA S3 bucket with the AWS CLI
	         run: |
	           aws s3 sync . s3://${{ env.BUCKET_NAME }} --follow-symlinks --delete --exclude '.git/*'