name: Deploy code to S3 bucket
on:
  push:
    branches:
      - main

jobs:
  deploy_to_s3:
    name: Deploy code to S3 bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      

      - name: Deploy to S3
        run: |
          aws s3 sync ./dags/sp-classifier s3://sp-classifier-mwaa/dags/sp-classifier --delete --region ${{ secrets.AWS_REGION }}
          aws s3 sync ./requirements s3://sp-classifier-mwaa/requirements --delete --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}